import '../styles/globals.css'
import { Header, Footer } from './../components'
import Head from 'next/head'
import React from 'react'
import PropTypes from 'prop-types'


const MyApp = ({ Component, pageProps }) => {
	return (
		<>
			<Head>
				<title>Bearpoint Blog: </title>
				<meta name="description" content="Generated by create next app" />
			</Head >
			<Header />
			<Component {...pageProps} />
			<Footer />
		</>
	)
}

MyApp.propTypes = {
	Component: PropTypes.any,
	pageProps: PropTypes.object
}

export default MyApp
