import '../styles/globals.css'
import { Header, Footer } from './../components'
import Head from 'next/head'
import React, { useEffect } from 'react'
import PropTypes from 'prop-types'
import hljs from 'highlight.js';
import 'highlight.js/styles/github.css';

const MyApp = ({ Component, pageProps }) => {
	useEffect(() => {
		hljs.highlightAll();
	}, [])
	return (
		<>
			<Head>
				<title>Bearpoint Blog: </title>
				<meta name="description" content="Generated by create next app" />
			</Head >
			<Header />
			<Component {...pageProps} />
			<Footer />
		</>
	)
}

MyApp.propTypes = {
	Component: PropTypes.any,
	pageProps: PropTypes.object
}

export default MyApp
